-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.emprunt
(
    id bigint NOT NULL DEFAULT nextval('emprunt_id_seq'::regclass),
    nom text COLLATE pg_catalog."default",
    date text COLLATE pg_catalog."default",
    date_retour text COLLATE pg_catalog."default",
    motif text COLLATE pg_catalog."default",
    materiel text COLLATE pg_catalog."default",
    CONSTRAINT emprunt_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.materiel
(
    id text COLLATE pg_catalog."default" NOT NULL,
    nature text COLLATE pg_catalog."default",
    date_entrer text COLLATE pg_catalog."default",
    date_fin text COLLATE pg_catalog."default",
    info text COLLATE pg_catalog."default",
    cout text COLLATE pg_catalog."default",
    etat text COLLATE pg_catalog."default",
    mode_migration text COLLATE pg_catalog."default",
    date_migration text COLLATE pg_catalog."default",
    CONSTRAINT materiel_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.personnel
(
    id text COLLATE pg_catalog."default" NOT NULL,
    nom text COLLATE pg_catalog."default",
    direction text COLLATE pg_catalog."default",
    site text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    CONSTRAINT personnel_pkey PRIMARY KEY (id)
);
END;